import {
  Activity,
  Aperture,
  Apple,
  Award,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Atom,
  Baby,
  Badge,
  BarChart3,
  Beef,
  Beer,
  Bell,
  Bike,
  Book,
  BookOpen,
  Bookmark,
  Bold,
  Box,
  Braces,
  Brush,
  Bug,
  Cake,
  Calendar,
  Camera,
  Candy,
  Car,
  Carrot,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Circle,
  CircleCheck,
  CircleDot,
  Citrus,
  Clipboard,
  Clock,
  Cloud,
  Coffee,
  Cog,
  Coins,
  Command,
  Compass,
  Copy,
  Salad,
  Cpu,
  Croissant,
  Crown,
  CupSoda,
  Dices,
  Download,
  Droplet,
  Egg,
  Equal,
  Eraser,
  Eye,
  EyeOff,
  File,
  FilePlus,
  FileText,
  Files,
  Filter,
  Flag,
  Flame,
  Flower,
  Folder,
  FolderOpen,
  FolderPlus,
  Gamepad2,
  Gauge,
  GitBranch,
  GlassWater,
  Globe,
  Grape,
  GripVertical,
  Hand,
  Hammer,
  Heading,
  Heart,
  HeartHandshake,
  HelpCircle,
  Hexagon,
  Home,
  IceCream,
  Image,
  Images,
  Info,
  Italic,
  KeyRound,
  Keyboard,
  Layers,
  LayoutGrid,
  LayoutList,
  Leaf,
  Library,
  Link,
  Link2,
  List,
  ListChecks,
  ListTree,
  Loader,
  Lock,
  Mail,
  Map,
  MapPin,
  Maximize,
  Menu,
  MessageCircle,
  Mic,
  Milk,
  Minimize,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Mountain,
  MousePointer,
  Move,
  Music,
  Newspaper,
  Notebook,
  NotebookPen,
  Package,
  Palette,
  Paperclip,
  PartyPopper,
  Pause,
  PenLine,
  PenTool,
  Pencil,
  Percent,
  Phone,
  PieChart,
  Pill,
  Pin,
  Pizza,
  Play,
  Plug,
  Pointer,
  Plus,
  Power,
  Printer,
  Puzzle,
  QrCode,
  Radio,
  Rainbow,
  Recycle,
  Redo2,
  RefreshCw,
  Repeat,
  RotateCcw,
  RotateCw,
  Ruler,
  Save,
  Scale,
  Scan,
  Scroll,
  Search,
  Send,
  Settings,
  Settings2,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Shuffle,
  Sidebar,
  SidebarOpen,
  Smile,
  SlidersHorizontal,
  SlidersVertical,
  Snowflake,
  Soup,
  Sparkles,
  Square,
  SquareCheck,
  Star,
  StickyNote,
  StopCircle,
  Cherry,
  Strikethrough,
  Sun,
  Sunrise,
  Tag,
  Tags,
  Target,
  Telescope,
  Terminal,
  Text,
  Timer,
  ToggleLeft,
  Trash2,
  TrendingUp,
  Triangle,
  Trophy,
  Truck,
  Tv,
  Type,
  Underline,
  Undo2,
  Unlink,
  Unlock,
  Upload,
  User,
  UserPlus,
  Users,
  Utensils,
  UtensilsCrossed,
  Volume,
  Wallet,
  Wand2,
  Waves,
  Wheat,
  Wifi,
  Wine,
  Wrench,
  X,
  Zap,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from 'lucide-react';

import { t } from '@/i18n';

/** Registro curado de ícones (nome kebab-case → componente lucide). */
export const ICONS = {
  activity: Activity,
  aperture: Aperture,
  apple: Apple,
  award: Award,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  atom: Atom,
  baby: Baby,
  badge: Badge,
  'bar-chart': BarChart3,
  beef: Beef,
  beer: Beer,
  bell: Bell,
  bike: Bike,
  book: Book,
  'book-open': BookOpen,
  bookmark: Bookmark,
  bold: Bold,
  box: Box,
  braces: Braces,
  brush: Brush,
  bug: Bug,
  cake: Cake,
  calendar: Calendar,
  camera: Camera,
  candy: Candy,
  car: Car,
  carrot: Carrot,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-up-down': ChevronsUpDown,
  circle: Circle,
  'circle-check': CircleCheck,
  'circle-dot': CircleDot,
  citrus: Citrus,
  clipboard: Clipboard,
  clock: Clock,
  cloud: Cloud,
  coffee: Coffee,
  cog: Cog,
  coins: Coins,
  command: Command,
  compass: Compass,
  copy: Copy,
  salad: Salad,
  cpu: Cpu,
  croissant: Croissant,
  crown: Crown,
  'cup-soda': CupSoda,
  dices: Dices,
  download: Download,
  droplet: Droplet,
  egg: Egg,
  equal: Equal,
  eraser: Eraser,
  eye: Eye,
  'eye-off': EyeOff,
  file: File,
  'file-plus': FilePlus,
  'file-text': FileText,
  files: Files,
  filter: Filter,
  flag: Flag,
  flame: Flame,
  flower: Flower,
  folder: Folder,
  'folder-open': FolderOpen,
  'folder-plus': FolderPlus,
  gamepad: Gamepad2,
  gauge: Gauge,
  'git-branch': GitBranch,
  'glass-water': GlassWater,
  globe: Globe,
  grape: Grape,
  'grip-vertical': GripVertical,
  hand: Hand,
  hammer: Hammer,
  heading: Heading,
  heart: Heart,
  'heart-handshake': HeartHandshake,
  help: HelpCircle,
  hexagon: Hexagon,
  home: Home,
  'ice-cream': IceCream,
  image: Image,
  images: Images,
  info: Info,
  italic: Italic,
  key: KeyRound,
  keyboard: Keyboard,
  layers: Layers,
  'layout-grid': LayoutGrid,
  'layout-list': LayoutList,
  leaf: Leaf,
  library: Library,
  link: Link,
  'link-2': Link2,
  list: List,
  'list-checks': ListChecks,
  'list-tree': ListTree,
  loader: Loader,
  lock: Lock,
  mail: Mail,
  map: Map,
  'map-pin': MapPin,
  maximize: Maximize,
  menu: Menu,
  message: MessageCircle,
  mic: Mic,
  milk: Milk,
  minimize: Minimize,
  monitor: Monitor,
  moon: Moon,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  mountain: Mountain,
  'mouse-pointer': MousePointer,
  move: Move,
  music: Music,
  newspaper: Newspaper,
  notebook: Notebook,
  'notebook-pen': NotebookPen,
  package: Package,
  palette: Palette,
  paperclip: Paperclip,
  party: PartyPopper,
  pause: Pause,
  'pen-line': PenLine,
  'pen-tool': PenTool,
  pencil: Pencil,
  percent: Percent,
  phone: Phone,
  'pie-chart': PieChart,
  pill: Pill,
  pin: Pin,
  pizza: Pizza,
  play: Play,
  plug: Plug,
  pointer: Pointer,
  plus: Plus,
  power: Power,
  printer: Printer,
  puzzle: Puzzle,
  'qr-code': QrCode,
  radio: Radio,
  rainbow: Rainbow,
  recycle: Recycle,
  redo: Redo2,
  refresh: RefreshCw,
  repeat: Repeat,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  ruler: Ruler,
  save: Save,
  scale: Scale,
  scan: Scan,
  scroll: Scroll,
  search: Search,
  send: Send,
  settings: Settings,
  'settings-2': Settings2,
  share: Share2,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shopping-cart': ShoppingCart,
  shuffle: Shuffle,
  sidebar: Sidebar,
  'sidebar-open': SidebarOpen,
  smile: Smile,
  sliders: SlidersHorizontal,
  'sliders-vertical': SlidersVertical,
  snowflake: Snowflake,
  soup: Soup,
  sparkles: Sparkles,
  square: Square,
  'square-check': SquareCheck,
  star: Star,
  'sticky-note': StickyNote,
  stop: StopCircle,
  cherry: Cherry,
  strikethrough: Strikethrough,
  sun: Sun,
  sunrise: Sunrise,
  tag: Tag,
  tags: Tags,
  target: Target,
  telescope: Telescope,
  terminal: Terminal,
  text: Text,
  timer: Timer,
  toggle: ToggleLeft,
  trash: Trash2,
  'trending-up': TrendingUp,
  triangle: Triangle,
  trophy: Trophy,
  truck: Truck,
  tv: Tv,
  type: Type,
  underline: Underline,
  undo: Undo2,
  unlink: Unlink,
  unlock: Unlock,
  upload: Upload,
  user: User,
  'user-plus': UserPlus,
  users: Users,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  volume: Volume,
  wallet: Wallet,
  wand: Wand2,
  waves: Waves,
  wheat: Wheat,
  wifi: Wifi,
  wine: Wine,
  wrench: Wrench,
  x: X,
  zap: Zap,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

/** Lista para o seletor de ícones, em ordem estável. */
export const ICON_NAMES = Object.keys(ICONS) as IconName[];

export function isIconName(value: string): value is IconName {
  return value in ICONS;
}

export function iconLabel(name: string): string {
  return isIconName(name) ? name.replace(/-/g, ' ') : t('picker.iconePadrao');
}
